### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by desyncr**
Small markdown fix. Sections "What Beluga Doesn't Do?" and "How is it working?" appeared squashed together.

Also "How is it working?" sounds strange to me. Shouldn't it be "How does it works?"?

### CODE REVIEW

**Comment by mrheaumecortex** [comment]
How does it works does indeed sound more smooth. 

Would you be ok to update this nit at the same time ?

Thanks a lot!

**Comment by desyncr** [comment]
Yeah sure, I'll add few other small spelling fixes as well.

**Comment by mrheaumecortex** [comment]
Awesome thanks.

**Comment by desyncr** [comment]
Alright. Updated and squashed.

Check it out and let me know what you think.

**Comment by mrheaumecortex** [comment]
Looks great !

Thanks!

**Comment by desyncr** [comment]
Amazing! Thanks!

**Pull request merged**
